<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Faker\Factory as FakerFactory;

class DocumentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = FakerFactory::create();
        DB::table('documents')->insert([
            [
                'id' => Str::uuid(),
                'title' => 'Informe de Evaluación de Personal',
                'reference_number' => 'DOC-1001',
                'description' => 'Informe detallado del rendimiento del personal administrativo.',
                'category_id' => 2,
                'status_id' => 2,
                'sender_department_id' => 3,
                'receiver_department_id' => 1,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'High',
                'created_by' => 2,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Solicitud de Vacaciones Colectivas',
                'reference_number' => 'DOC-1002',
                'description' => 'Petición de vacaciones para el área de Recursos Humanos.',
                'category_id' => 1,
                'status_id' => 1,
                'sender_department_id' => 4,
                'receiver_department_id' => 1,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'Medium',
                'created_by' => 2,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Acta de Evaluación de Personal',
                'reference_number' => 'DOC-1003',
                'description' => 'Acta oficial de evaluación semestral.',
                'category_id' => 2,
                'status_id' => 3,
                'sender_department_id' => 5,
                'receiver_department_id' => 1,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'Low',
                'created_by' => 2,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Oficio de Renovación de Contratos',
                'reference_number' => 'DOC-1004',
                'description' => 'Notificación de renovación de contratos del personal.',
                'category_id' => 1,
                'status_id' => 1,
                'sender_department_id' => 6,
                'receiver_department_id' => 1,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'Medium',
                'created_by' => 2,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Solicitud de Cambio de Horario',
                'reference_number' => 'DOC-1005',
                'description' => 'Requerimiento de modificación de horario laboral.',
                'category_id' => 1,
                'status_id' => 2,
                'sender_department_id' => 7,
                'receiver_department_id' => 1,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'Low',
                'created_by' => 2,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Solicitud de Evaluación de Desempeño',
                'reference_number' => 'DOC-2003',
                'description' => 'Solicitud para iniciar proceso de evaluación del personal administrativo.',
                'category_id' => 1,
                'status_id' => 1,
                'sender_department_id' => 1, // Recursos Humanos
                'receiver_department_id' => 2, // Subdirección de Recursos Humanos
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'High',
                'created_by' => 3,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Acta de Comité de Evaluación',
                'reference_number' => 'DOC-2004',
                'description' => 'Resultados de la evaluación semestral de desempeño.',
                'category_id' => 2,
                'status_id' => 3,
                'sender_department_id' => 4,
                'receiver_department_id' => 2,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'Medium',
                'created_by' => 3,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Informe de Asistencia de Personal',
                'reference_number' => 'DOC-2005',
                'description' => 'Informe trimestral de asistencia de los trabajadores.',
                'category_id' => 4,
                'status_id' => 2,
                'sender_department_id' => 5,
                'receiver_department_id' => 2,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'Low',
                'created_by' => 3,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Oficio de Reasignación de Personal',
                'reference_number' => 'DOC-2006',
                'description' => 'Notificación de cambios de área para empleados administrativos.',
                'category_id' => 1,
                'status_id' => 4,
                'sender_department_id' => 6,
                'receiver_department_id' => 2,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'Medium',
                'created_by' => 3,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Solicitud de Contratación por Suplencia',
                'reference_number' => 'DOC-2007',
                'description' => 'Solicitud temporal por ausencia prolongada de personal.',
                'category_id' => 1,
                'status_id' => 1,
                'sender_department_id' => 3,
                'receiver_department_id' => 2,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'High',
                'created_by' => 3,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Solicitud de Pago Extraordinario',
                'reference_number' => 'DOC-3001',
                'description' => 'Solicitud de pago por horas extra del mes de abril.',
                'category_id' => 1,
                'status_id' => 1,
                'sender_department_id' => 1, // Dirección de Recursos Humanos
                'receiver_department_id' => 3, // Nómina
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'High',
                'created_by' => 4,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Informe de Cálculo de Aguinaldo',
                'reference_number' => 'DOC-3002',
                'description' => 'Cálculo estimado del pago de aguinaldo para fin de año.',
                'category_id' => 4,
                'status_id' => 2,
                'sender_department_id' => 4, // Dirección de Control Presupuestal
                'receiver_department_id' => 3,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'Medium',
                'created_by' => 4,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Oficio de Notificación de Incremento Salarial',
                'reference_number' => 'DOC-3003',
                'description' => 'Autorización para el ajuste salarial por nivel de desempeño.',
                'category_id' => 1,
                'status_id' => 3,
                'sender_department_id' => 5, // Archivo
                'receiver_department_id' => 3,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'High',
                'created_by' => 4,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Acta de Revisión de Tabulador Salarial',
                'reference_number' => 'DOC-3004',
                'description' => 'Revisión semestral de tabulador de sueldos y salarios.',
                'category_id' => 2,
                'status_id' => 4,
                'sender_department_id' => 6,
                'receiver_department_id' => 3,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'Low',
                'created_by' => 4,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Reporte de Deducciones Mensuales',
                'reference_number' => 'DOC-3005',
                'description' => 'Informe detallado de deducciones por quincena.',
                'category_id' => 4,
                'status_id' => 5,
                'sender_department_id' => 2,
                'receiver_department_id' => 3,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'Medium',
                'created_by' => 4,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],

            [
                'id' => Str::uuid(),
                'title' => 'Informe Trimestral de Presupuesto',
                'reference_number' => 'DOC-4001',
                'description' => 'Informe del uso presupuestal correspondiente al primer trimestre.',
                'category_id' => 4,
                'status_id' => 2,
                'sender_department_id' => 1,
                'receiver_department_id' => 4,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'Medium',
                'created_by' => 5,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Solicitud de Redistribución Presupuestal',
                'reference_number' => 'DOC-4002',
                'description' => 'Petición para redistribuir partidas presupuestales entre departamentos.',
                'category_id' => 1,
                'status_id' => 1,
                'sender_department_id' => 3,
                'receiver_department_id' => 4,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'High',
                'created_by' => 5,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Acta de Aprobación de Proyecto',
                'reference_number' => 'DOC-4003',
                'description' => 'Acta de reunión para la aprobación del proyecto de inversión institucional.',
                'category_id' => 2,
                'status_id' => 3,
                'sender_department_id' => 2,
                'receiver_department_id' => 4,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'High',
                'created_by' => 5,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Oficio de Asignación de Recursos',
                'reference_number' => 'DOC-4004',
                'description' => 'Asignación oficial de recursos para actividades académicas.',
                'category_id' => 1,
                'status_id' => 4,
                'sender_department_id' => 6,
                'receiver_department_id' => 4,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'Medium',
                'created_by' => 5,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Reporte de Inventarios Departamentales',
                'reference_number' => 'DOC-4005',
                'description' => 'Resumen de inventarios entregado por cada departamento.',
                'category_id' => 4,
                'status_id' => 5,
                'sender_department_id' => 5,
                'receiver_department_id' => 4,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'Low',
                'created_by' => 5,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Acta de Transferencia Documental',
                'reference_number' => 'DOC-5001',
                'description' => 'Acta para el traspaso de documentos a la unidad de archivo.',
                'category_id' => 2,
                'status_id' => 1,
                'sender_department_id' => 2,
                'receiver_department_id' => 5,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'Medium',
                'created_by' => 6,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Solicitud de Resguardo de Expediente',
                'reference_number' => 'DOC-5002',
                'description' => 'Solicitud para el resguardo de expediente académico.',
                'category_id' => 1,
                'status_id' => 2,
                'sender_department_id' => 3,
                'receiver_department_id' => 5,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'High',
                'created_by' => 6,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Informe de Documentación Histórica',
                'reference_number' => 'DOC-5003',
                'description' => 'Informe sobre documentos históricos recuperados.',
                'category_id' => 4,
                'status_id' => 4,
                'sender_department_id' => 1,
                'receiver_department_id' => 5,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'Low',
                'created_by' => 6,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Oficio de Digitalización de Archivos',
                'reference_number' => 'DOC-5004',
                'description' => 'Oficio que solicita la digitalización de archivos físicos.',
                'category_id' => 1,
                'status_id' => 3,
                'sender_department_id' => 6,
                'receiver_department_id' => 5,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'Medium',
                'created_by' => 6,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],
            [
                'id' => Str::uuid(),
                'title' => 'Acta de Depuración de Expedientes',
                'reference_number' => 'DOC-5005',
                'description' => 'Acta de reunión para definir los expedientes a depurar.',
                'category_id' => 2,
                'status_id' => 5,
                'sender_department_id' => 4,
                'receiver_department_id' => 5,
                'issue_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'priority' => 'High',
                'created_by' => 6,
                'received_date' => $faker->dateTimeBetween('-1 year', 'now'),
                'created_at' => $faker->dateTimeBetween('-1 year', 'now'),
            ],



        ]);
    }
}
